deploy: False
tag: "minLM_run1"
seed: 0

device: "cuda:0"
epochs: 50

net:
  compile: True
  vocab_size: 512
  context_size: 32
  n_layer: 12
  n_head: 12
  n_embd: 120
  dropout: 0.0
  bias: False

optimizer:
  learning_rate: 3e-4
  weight_decay: 1e-1
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0

  decay_lr: True
  min_lr: 3e-5

log: 
  eval_interval: 200
  log_interval: 10

 
# Nested configs. Disable hydra logging
defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

# Disable hydra directory structure
hydra:
  output_subdir: Null
  job:
    chdir: False
  run:
    dir: .

  sweep:
    dir: .
    subdir: .
