deploy: False
tag: "minLM"
run_name: "run2"
seed: 0

device: "cuda:0"
total_iters: 600000

data:
  train_file: "data/wikitext103/wikitext103_train.npy"
  val_file: "data/wikitext103/wikitext103_validation.npy"
  bs: 32
  nworkers: 2
  title: False

net:
  compile: True
  vocab_size: 50257
  context_size: 512
  n_layer: 12
  n_head: 12
  n_embd: 1080
  bias: False
  dropout: 0.0
  position_encoding: 'learnable' # 'learnable', 'sinusoidal'

optimizer:
  learning_rate: 1e-4
  min_lr: 2e-5
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  weight_decay: 1e-1
  grad_accumulation: 40
  use_scaler: True
  warmup_iters: 0
  decay_lr: True

log: 
  eval_interval: 5000
  eval_batches: 500
  log_interval: 500
  save_interval: 100000

 
# Nested configs. Disable hydra logging
defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

# Disable hydra directory structure
hydra:
  output_subdir: Null
  job:
    chdir: False
  run:
    dir: .

  sweep:
    dir: .
    subdir: .
