deploy: False
tag: "minLM"
run_name: "run2"
seed: 0

device: "cuda:0"
total_iters: 600000

data:
  bs: 32
  tokenizer: "openai-community/gpt2"
  subsample: 1.0
  min_len: 1
  nworkers: 2
  title: False

net:
  compile: True
  vocab_size: 50258
  context_size: 512
  n_layer: 12
  n_head: 12
  n_embd: 1080
  bias: False

optimizer:
  learning_rate: 3e-4
  weight_decay: 1e-1
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  grad_accumulation: 20
  ignore_eos: False
  use_scaler: True
  warmup_iters: 0
  decay_lr: True
  min_lr: 3e-5

log: 
  eval_interval: 5000
  log_interval: 500
  save_interval: 50000

 
# Nested configs. Disable hydra logging
defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

# Disable hydra directory structure
hydra:
  output_subdir: Null
  job:
    chdir: False
  run:
    dir: .

  sweep:
    dir: .
    subdir: .
