deploy: False
tag: "minLM_run1"
seed: 0

device: "cpu" # "cuda:0"
total_iters: 10000

data:
  bs: 32
  tokenizer: "openai-community/gpt2"
  subsample: 0.001

net:
  compile: True
  vocab_size: 50258
  context_size: 256
  n_layer: 4
  n_head: 1
  n_embd: 256
  dropout: 0.0
  bias: False

optimizer:
  learning_rate: 3e-4
  weight_decay: 1e-1
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  grad_accumulation: 10
  use_scaler: True

  warmup_iters: 0
  decay_lr: True
  min_lr: 3e-5

log: 
  eval_interval: 1000
  log_interval: 100

 
# Nested configs. Disable hydra logging
defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

# Disable hydra directory structure
hydra:
  output_subdir: Null
  job:
    chdir: False
  run:
    dir: .

  sweep:
    dir: .
    subdir: .
