deploy: False
tag: "minLM"
run_name: "run2"
seed: 0

device: "cuda:0"
total_iters: 600000

data:
  train_file: "data/wikitext103/wikitext103_train.json"
  val_file: "data/wikitext103/wikitext103_validation.json"
  bs: 32
  nworkers: 2
  title: False

net:
  compile: True
  context_size: 1024
  n_layer: 12
  n_head: 12
  n_embd: 1080
  bias: False
  dropout: 0.0
  position_encoding: 'learnable' # 'learnable', 'sinusoidal'

optimizer:
  learning_rate: 3e-4
  weight_decay: 1e-1
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  grad_accumulation: 20
  ignore_eos: False
  use_scaler: True
  warmup_iters: 0
  decay_lr: True
  min_lr: 3e-5

log: 
  eval_interval: 5000
  log_interval: 500
  save_interval: 50000

 
# Nested configs. Disable hydra logging
defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

# Disable hydra directory structure
hydra:
  output_subdir: Null
  job:
    chdir: False
  run:
    dir: .

  sweep:
    dir: .
    subdir: .
